### ISSUE TITLE
Will other frameworks be supported?

### ISSUE THREAD

**Issue by jseekamp** [coreyward/sanity-image#24]
I have a nuxt project that is in dire need of this component. Will there be a framework independent version of this developed in the future or a nuxt version?

**Comment by coreyward** [comment]
I've never used Vue before, but most of the heavy lifting isn't React-specific, so ostensibly this would be straightforward, but there are downsides to supporting both targets in the same package (e.g., declaring peer dependencies, versioning noise, unrelated CHANGELOG entries). 

It might be a better approach for me to extract the non-React bits that do the heavy lifting (`urlBuilder`, `parseImageId`, and the prop-assembly logic in `SanityImage`) into a generic JS package that can be consumed by `sanity-image` and any other packages. If I were to do that, would you be interested in building and maintaining a Vue/Nuxt compatible package?

**Comment by coreyward** [comment]
I'm going to close this for now since I haven't heard back, but if you (or anybody stumbling across this in the future) would like to see a vanilla JS library with the relevant functions in order to build on top of let me know and I'll see about refactoring to support that.
