### ISSUE TITLE
Getting started and usage of Sanity Image

### ISSUE THREAD

**Issue by AMarlonG** [coreyward/sanity-image#25]
Hi!

I'm a total newbie who has arrived late for the dev party, so I ask a lot of dumb questions.
The "dumb" request now is that it would help us newbies with no experience to get started with this component if you explained in the README where your code is going, and what you need to get it up and running in the studio.
A bit like is explained with the Media browser plugin: https://github.com/sanity-io/sanity-plugin-media#usage
Here it says where the code goes, etc.

I know 99% probably understand how to get this going, but I, for one, is just understanding that this is a great component, but cant' get started ...

**Comment by coreyward** [comment]
Hi @AMarlonG, there are several examples of how to use the component in the README. It works in any React environment, but explaining how to set up various React applications is beyond the scope of this library.
