### ISSUE TITLE
Question: lazy loading with translateX images

### ISSUE THREAD

**Issue by simonhrogers** [coreyward/sanity-image#28]
Hey Corey, 

Do you have any plans to support this? I think it would be a really useful feature but I’ll make a hacky solution if not. 

It accounts for a variety of possibilities likely to occur in modern web applications like scroll transitions and many popular slideshow frameworks e.g. Swiper. It was handled very elegantly by the old `lazysizes` package. 

I’d really appreciate your thoughts. 

Thanks again,

Simon

**Comment by coreyward** [comment]
Can you maybe create a demo or mock up to help me understand what the problem is? Browser-native lazy loading should work fine provided you are including markup in the DOM.

**Comment by simonhrogers** [comment]
@coreyward so sorry to waste your time – this was a simple case of me misinterpreting the documentation. Thanks for your reply it helped me realise my mistake. Closing!
