### ISSUE TITLE
Wrap it internally example does not give accurate prop types

### ISSUE THREAD

**Issue by georgeosutton** [coreyward/sanity-image#29]
```
import { SanityImage } from "sanity-image"

const projectId = process.env.SANITY_PROJECT_ID
const dataset = process.env.SANITY_DATASET
const baseUrl = `https://cdn.sanity.io/images/${projectId}/${dataset}/`

export const Image = (
  props: Omit<
    React.ComponentProps<typeof SanityImage>,
    "baseUrl" | "dataset" | "projectId"
  >
) => <SanityImage baseUrl={baseUrl} {...props} />
```
Getting the following type error. 

Property 'id' is missing in type '{ baseUrl: string; }' but required in type 'ImageQueryInputs'.

If I remove the Omit it gets rid of the error but then I'm noticing things like className don't autocomplete.

**Comment by coreyward** [comment]
Yeah, this is strange. Seems like a TS bug to me since the following still requires `id`, but I’m not really confident I know what is happening.

```ts
// still requires `id` despite TS complaints otherwise
Omit<
  React.ComponentProps<typeof SanityImage>,
  "baseUrl" | "dataset" | "projectId"
>
```

I use a slight variation on this that doesn’t omit `baseUrl`, `dataset`, and `projectId` if you are comfortable with that: 

```tsx
import { SanityImage } from "sanity-image"

const projectId = process.env.SANITY_PROJECT_ID
const dataset = process.env.SANITY_DATASET
const baseUrl = `https://cdn.sanity.io/images/${projectId}/${dataset}/`

export const Image = (props: React.ComponentProps<typeof SanityImage>) => (
  <SanityImage baseUrl={baseUrl} {...props} />
)
```

For some reason this only works with `ComponentProps`, or `ComponentPropsWithRef`, but not `ComponentPropsWithoutRef`, so be mindful of that.

**Comment by georgeosutton** [comment]
In order to get the expected img tag attributes in props I had to add & React.ComponentProps<"img">.

```
"use client";
import { SanityImage } from "sanity-image";

export const Image = (props: React.ComponentProps<typeof SanityImage> & React.ComponentProps<"img">) => (
  <SanityImage {...props} />
);
```
Also I'm wrapping so I can add the "use client" directive so I can use the component inside server components in the Next.js app directory so not including the omit is fine.

Is it possible to add this directive to the package so I don't have to create a wrapper?

**Comment by coreyward** [comment]
The only portion of `SanityImage` that requires client-side is the low-quality image previews, and I'm hoping to remove the need for that to be client-side in the somewhat near future. I recommend using a wrapper in your app in any case to provide configuration and to have a shared path for extending and augmenting images in your app in the future.

**Comment by georgeosutton** [comment]
Okay sounds good. Appreciate your time on this.
