### ISSUE TITLE
How to preload image to improve LCP score?

### ISSUE THREAD

**Issue by codingChewie** [coreyward/sanity-image#32]
Utilizing `SanityImage` to serve up a hero with a background image above-the-fold Lighthouse indicates to improve my LCP time to:

> Preload the image used by the LCP element in order to improve your LCP time. 

and links to my image and [docs](https://web.dev/optimize-lcp/?utm_source=lighthouse&utm_medium=node#preload-important-resources). In `SanityImage` is there a way to preload the image or implement the approach in a `useEffect` like:

```
import { useEffect, useState } from 'react';

export const useImageLoader = (initialSrc: string, currentSrc: string) => {
  const [imageSrc, _setImageSrc] = useState(initialSrc);

  useEffect(() => {
    const img = new Image();
    img.onload = () => {
      _setImageSrc(currentSrc);
    };
    img.src = currentSrc;
  }, [currentSrc]);

  return [imageSrc];
};
```

what is the best solution to resolve this issue?

**Comment by coreyward** [comment]
See #31 w/r/t `rel="preload"`. Doing what you've shown is very outdated and does not allow for any of the modern optimizations like `srcset`, `loading`, or `sizes`.
