### ISSUE TITLE
Animation on native lazy load – onLoadingComplete or [data-loading] attribute to help determine when images are loaded?

### ISSUE THREAD

**Issue by simonhrogers** [coreyward/sanity-image#38]
Hey Corey, 

I suspect you’ve made a decision not to accommodate this – but I am personally very fond of having the option to fade images in once loaded. With `next/image` this can be done with `onLoadingComplete`, as `onLoad` isn’t triggered for cached images. With `lazysizes` this was always easy because convenient classes were appended at different states. 

You mention a `[data-loading]` attribute in the docs but I can’t see this being applied or removed for unloaded `img` elements. 

I’ve also seen examples where a ref is used, but obviously I cannot pass a ref to the `sanity-image` component. 

Sorry that this is more of a question – would be very grateful for any pointers in the right direction. 

Many thanks, 

Simon

**Comment by coreyward** [comment]
Hey Simon! The `[data-loading]` attributes are added if you have a preview image. E.g.: 
https://github.com/coreyward/sanity-image/blob/bbe1a276d0abf86ba6baa65598aa53afa85fe727/src/ImageWithPreview.tsx#L44

For doing animation work, I think it's easier to just provide a custom component instead of using an `img` element directly. For example: 

```js
const YourImage = (...props) => {
  if (props["data-lqip"]) {
    // this is the low quality preview image being rendered
    return <img {...props} />
  } else {
    // this is the full-size image being rendered
    return <img {...props} />
  }
}

// elsewhere…
<SanityImage as={YourImage} {...otherProps} />
```

In either case, you have control of which props are passed down and are able to use things like Framer Motion, GSAP, or even just custom CSS to manipulate what is shown. If you have to override the `onLoad` handler, just be sure to either remove the preview image or call `props.onLoad`.

Good luck!

**Comment by simonhrogers** [comment]
Many thanks Corey :-) I’ll check this out.

**Comment by simonhrogers** [comment]
Corey thank you so much again for taking the time to reply, it really helped correct another misunderstanding I had made. 

Just leaving this here incase it helps anyone cruising the web for the same thing :-)

A reliable fade transition (no preview image) on native lazy load. If images are cached in Chrome the `ref.current.complete` will still work. 

```javascript
import { SanityImage } from "sanity-image"
import { dataset, projectId } from 'lib/sanity.api'

import styles from "./SanityImage.module.scss"
import { useState, useEffect, useRef } from "react";

const baseUrl = `https://cdn.sanity.io/images/${projectId}/${dataset}/`

const FadeImage = (props) => {
  const [loaded, setLoaded] = useState(false)
  const ref = useRef(null)

  useEffect(() => {
    if (ref && ref.current && ref.current.complete) {
      setLoaded(true)
    }
  }, [])

  useEffect(() => {
    if (loaded && ref && ref.current) {
      ref.current.removeAttribute('data-loading')
    }
  }, [loaded])

  return (
    <img
      ref={ref}
      onLoad={() => setLoaded(true)}
      data-loading
      {...props} 
    />
  )
}

export const Image = (props: Omit<
  React.ComponentProps<typeof SanityImage>,
  "baseUrl" | "dataset" | "projectId"
>) => {

  const { image, classNames, useAspectRatio } = props
  const { id, preview, aspectRatio } = image  

  return (
    <SanityImage
      as={FadeImage}
      key={id}
      id={id}
      baseUrl={baseUrl}
      // preview={preview}
      className={`${styles.image} ${classNames}`}
      style={useAspectRatio ? { aspectRatio } : undefined}
    />
  )
}
```
